services:
  ### Nginx ####################################################
  nginx:
    build:
      context: ./docker/nginx
      args:
        - PHP_UPSTREAM_CONTAINER=php-fpm
        - PHP_UPSTREAM_PORT=9000
    volumes:
      - ./:/var/www:cached
      - ./docker/docker-runtime/nginx/log:/var/log/nginx
      - ./docker/nginx/local/sites:/etc/nginx/sites-available
    ports:
      - "8000:80"
    expose:
      - "8000"
    depends_on:
      - php-fpm
    links:
      - php-fpm
  ### PHP-FPM ##############################################
  php-fpm:
    image: registry.cn-hangzhou.aliyuncs.com/donny-zzk/laravel-php-fpm:v8.1
    #        build:
    #            context: ./docker/php-fpm
    #            args:
    #                - LARADOCK_PHP_VERSION=8.2
    #                - INSTALL_PHPREDIS=true
    #                - INSTALL_OPCACHE=true
    #                - INSTALL_MYSQLI=true
    #                - INSTALL_SWOOLE=true
    #                - INSTALL_IMAGEMAGICK=false
    #                - INSTALL_ADDITIONAL_LOCALES=false
    volumes:
      - ./docker/php-fpm/php8.0.ini:/usr/local/etc/php/php.ini
      - ./:/var/www:cached
    depends_on:
      - mysql
      - redis
    expose:
      - 9000
    logging:
      options:
        max-file: "5"
        max-size: "10m"
  ### MySQL ################################################
  mysql:
    platform: linux/x86_64
    build:
      context: ./docker/mysql
      args:
        - MYSQL_VERSION=8.0
    environment:
      - MYSQL_USERNAME=root
      - MYSQL_ROOT_PASSWORD=123456
      - TZ=Asia/Shanghai
    volumes:
      - ./docker/docker-runtime/mysql:/var/lib/mysql
      - ./docker/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "33060:3306"

  ### Redis ################################################
  redis:
    image: redis:latest
    volumes:
      - ./docker/docker-runtime/redis:/data
    ports:
      - "6379:6379"
    logging:
      options:
        max-file: "5"
        max-size: "10m"
